strictmode: false
url: http://localhost:5551
http:
  public:
    address: :5551
  internal:
    address: :1323
auth:
  contractvalidators: [employeeid]
vdr:
  didmethods: [web]
discovery:
  server:
    ids: ["hackathon_v2024"]
  client:
    refresh_interval: 50s
