strictmode: false
url: http://localhost:5551
didmethods: [web]
http:
  public:
    address: :5551
  internal:
    address: :1323
auth:
  contractvalidators: [employeeid]
vdr:
  didmethods: [web] # moved in 6.0.0-rc.6 release to didmethods (root config). left there since it does not impact node startup.
discovery:
  server:
    ids: ["hackathon_v2024"]
  client:
    refresh_interval: 50s
